
library(shiny)
library(dplyr)
library(ggplot2)
library(readr)
library(shinythemes)
ui <- fluidPage(theme = shinytheme("simplex"),

    # Application title
    titlePanel("Explore the CLT with Boston Housing Data"),

    # Sidebar 
    sidebarLayout(
        sidebarPanel(
            sliderInput("N",
                        "Sample How Many?",
                        min = 1,
                        max = 333,
                        value = 30),
            sliderInput("Repetitions",
                        "How Many Repeated Samples??",
                        min = 1,
                        max = 1000, 
                        value = 30)
        ), #sidebar layout


        mainPanel(
            tabsetPanel(type = "tabs",
                        
                #TAB ONE        
                tabPanel("about", tags$p("I listened to the Central Limit Theorem / Normal Distsribution episode of", tags$a(href="http://lineardigressions.com/episodes/2018/12/9/the-normal-distribution-and-the-central-limit-theorem", "Linear Digressions"), "while running some errands tonight and I got to thinking about making a simulation of the Central Limit Theorem based on their episode. Ben and Katie use the Boston Housing Prices dataset as a point of departure, so I pulled a sample of the dataset from", tags$a(href = "https://www.kaggle.com/c/boston-housing/", "Kaggle."), "This allows us to simulate the repeated-draws of the CLT on the housing price variable to get an understanding of how it better approximates a normal distribution as the number of draws increases."), #tags$p
                         tags$p("The actual mean of the dataset is 22.77 for the 333 observations randomly drawn by Kaggle. The actual distribution is shown here, followed by a distribution generated by you (see the controls on the sidebar). The Central Limit Theorem says that, no matter the underlying distribution of the data, the distribution of means generated by pulling repeated random samples will be Gaussian / Normally distributed. This marvellous fact allows for significance testing in statistics and is the link between probability that underlies much of the work being done when we do statistics.")#tags$p
                         ),

                # Tab TWO  
                tabPanel("plots",             # Show a plot of the generated distribution
                         plotOutput("originaldistPlot"),
                         plotOutput("cltdistPlot")
                         )
   
            ) #tabsetpanel
        ) #main panel
    )#sidebarlayout
)#fluidpage

# Define server logic
server <- function(input, output) {
    boston<-read_csv("train.csv")
    
    # returns a single value; not necessary for operation of shiny app.
    clt_draw<-function(var, n, repetitions) {
        mus <- as.data.frame(NULL)
        for (i in 1:repetitions){
            samp<-sample(var, n)
            mu <- mean(samp, na.rm = T)
            mus<- rbind(mus, mu)
        }
        return(mean(mus[,1], na.rm = TRUE))
    }
    
    # generates a vector of means from samples
    clt_generate<-function(var, n, repetitions) {
        mus <- as.data.frame(NULL)
        for (i in 1:repetitions){
            samp<-sample(var, n)
            mu <- mean(samp, na.rm = T)
            mus<- rbind(mus, mu)
        }
        return(mus)
    }
    # produces a histogram of original distribution. 
    output$originaldistPlot <- renderPlot({
            ggplot(data = boston, aes(x = medv)) + geom_histogram() +
            geom_vline(aes(xintercept = mean(medv, na.rm = TRUE))) +
            geom_text(aes(
                label = round(mean(medv, na.rm = TRUE), 2),
                x = mean(medv, na.rm = TRUE), y = -.05)) +
            labs(
                title = "Actual Distribution of Values", 
                x = "Median House Price"
            ) + theme_light()
    })
    # produces a histogram of sample means. 
    output$cltdistPlot <- renderPlot({
        clt_generate(boston$medv, n = input$N, repetitions = input$Repetitions) %>%
            rename(val = !!names(.[1])) %>%
            ggplot(aes(x = val)) + geom_histogram(bins = 20) +
            geom_vline(aes(xintercept = mean(val, na.rm = TRUE))) +
            geom_text(aes(
                label = round(mean(val, na.rm = TRUE), 2),
                x = mean(val, na.rm = TRUE), y = -.05)) +
            labs(
                title = "Distribution of Sample Means", 
                x = "Mean House Price of Sample"
            ) + theme_light()
    })
}

# Run the application 
shinyApp(ui = ui, server = server)
